### PR TITLE
[ZAB-13]Traning submiting to vatusa

### PR DESCRIPTION
**Pull request by Frafire**
## [ZAB-13]

---

### Summary

What does this PR do?
Create a form for send at the end of a traning lesson the report to VATUSA HQ
---

### DB Changes (if any)

- [] What is the change?
- Create submission form
- Create POST in VATUSA api by axios
```
changes here
```

---

### Testing

1. Run all tests.
2. Additional testing requirements...

---

### Post-Deployment Validation

How to verify in the production environment.

---

[ZAB-13]: https://zabartcc.atlassian.net/browse/ZAB-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Frafire** [comment]
#32

**Comment by cdconn00** [comment]
What steps can I take to test this? @Frafire

**Comment by cdconn00** [comment]
@Frafire Here is what the PR should look like, these are still not being formatted properly:



## [ZAB-13]

---

### Summary


- Create a form for send at the end of a traning lesson the report to VATUSA HQ

---

(DB Changes is deleted since there weren't any changes to the database)

---

### Testing

1. Run all tests.
2. *Here's where you put steps telling the reviewer how they can test your feature*

---

### Post-Deployment Validation

*Here is where you tell the reviewer how to verify the feature is working correctly when we release into production.*

---


[ZAB-13]: https://zabartcc.atlassian.net/browse/ZAB-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Frafire** [comment]
> What steps can I take to test this? @Frafire 

in this moment is impossible because the traning page dosen't loading i wanna try it in the beta website and submit test traning records

**Comment by cdconn00** [comment]
> > What steps can I take to test this? @Frafire
> 
> in this moment is impossible because the traning page dosen't loading i wanna try it in the beta website and submit test traning records

Okay, let's address that issue first. We shouldn't open up PRs for logic we cannot test.

**Comment by cdconn00** [comment]
@Frafire I have fixed the issue preventing you from testing this. I merged the change into this branch. Please reopen when this is ready to review and is testable.

**Pull request closed without merging**
